annotations:
  headlamp/plugin/archive-url: "https://github.com/headlamp-k8s/plugins/releases/download/prometheus-0.0.2/prometheus-0.0.2.tgz"
  headlamp/plugin/archive-checksum: "8df9109a2f3a7604f63f7d3f462435e4"
  headlamp/plugin/version-compat: ">=1.2.3"
  headlamp/plugin/distro-compat: "in-cluster,web,docker-desktop"
